### ISSUE TITLE
JavaScript head out of memory

### ISSUE THREAD

**Issue by Artim96** [dionysius/vaultwarden-web-vault-deb#3]
For some reason, building fails with an out of memory error. Is it knows how much this needs? I have 30 GB of storage free and 12 GB of memory available. In my opinion this should be enough. Or may it be because I need to compile with nodejs 20, as other software running on the server this will run on has other software not running that well with v18?

![Screenshot from 2024-06-06 13-16-58](https://github.com/dionysius/vaultwarden-web-vault-deb/assets/16918678/775bfb81-7721-4477-88b6-fa2508c7d59a)

**Comment by dionysius** [comment]
I believe the same underlying issue as with your vaultwarden build https://github.com/dionysius/vaultwarden-deb/issues/13. Your build system lacks enough memory. I am not really sure what the memory requirements really are for building.

**Comment by dionysius** [comment]
Building this locally on my laptop (with other tools open and full desktop environment) the full system memory usage peaked at 11.5GB.

**Comment by Artim96** [comment]
I'll check that out. I'll have to set up a different VM as compiling this consistently crashes VirtualBox lol. But as the vaultwarden deb did build, it shouldn't be an issue I guess.

**Comment by Artim96** [comment]
Only used little over 5 GB of memory. Going through QEMU/KVM and virt-manager is much more stable.
